Testing out test extraction.

diff --git a/.github/workflows/test-and-deploy.yml b/.github/workflows/test-and-deploy.yml
--- a/.github/workflows/test-and-deploy.yml
+++ b/.github/workflows/test-and-deploy.yml
@@ -39,7 +39,16 @@ jobs:
       run: npm run build-prod
 
     - name: Run tests
-      run: ./scripts/travis.sh
+      run: |
+        npm run markdown-lint
+        if ! bundle exec ./scripts/htmlproofer.rb;
+        then
+          echo "Failed HTML link validation."
+          exit 1;
+        else
+          echo -e "\xE2\x9C\x94 No broken internal/external links!"
+          exit 0;
+        fi
 
     - name: Deploy
       env:
